window.AML_TEAM_DATA = {
  "apollo": {
    "rebranded": "No",
    "owner": "Malcolm",
    "regularSeasonRecord": "28-6",
    "divisionTitles": "0",
    "playoffAppearances": "2",
    "playoffRecord": "1-2",
    "superBowlAppearances": "0",
    "superBowlWins": "0",
    "franchiseMvps": "0"
  },
  "black-cats": {
    "rebranded": "No",
    "owner": "Loot Fien",
    "regularSeasonRecord": "4-30",
    "divisionTitles": "0",
    "playoffAppearances": "0",
    "playoffRecord": "0-0",
    "superBowlAppearances": "0",
    "superBowlWins": "0",
    "franchiseMvps": "0"
  },
  "blizzards": {
    "rebranded": "No",
    "owner": "Icczz",
    "regularSeasonRecord": "21-13",
    "divisionTitles": "0",
    "playoffAppearances": "1",
    "playoffRecord": "0-1",
    "superBowlAppearances": "0",
    "superBowlWins": "0",
    "franchiseMvps": "0"
  },
  "dragons": {
    "rebranded": "No",
    "owner": "Lemon Juice",
    "regularSeasonRecord": "12-22",
    "divisionTitles": "0",
    "playoffAppearances": "0",
    "playoffRecord": "0-0",
    "superBowlAppearances": "0",
    "superBowlWins": "0",
    "franchiseMvps": "0"
  },
  "ducks": {
    "rebranded": "Yes — formerly Cheesesteaks",
    "owner": "MvP",
    "regularSeasonRecord": "13-21",
    "divisionTitles": "1",
    "playoffAppearances": "1",
    "playoffRecord": "0-1",
    "superBowlAppearances": "0",
    "superBowlWins": "0",
    "franchiseMvps": "0"
  },
  "empire": {
    "rebranded": "No",
    "owner": "Echo",
    "regularSeasonRecord": "14-19-1",
    "divisionTitles": "0",
    "playoffAppearances": "0",
    "playoffRecord": "0-0",
    "superBowlAppearances": "0",
    "superBowlWins": "0",
    "franchiseMvps": "0"
  },
  "falcons": {
    "rebranded": "No",
    "owner": "Kfjaa",
    "regularSeasonRecord": "22-12",
    "divisionTitles": "0",
    "playoffAppearances": "2",
    "playoffRecord": "1-2",
    "superBowlAppearances": "0",
    "superBowlWins": "0",
    "franchiseMvps": "0"
  },
  "flamingos": {
    "rebranded": "No",
    "owner": "Chazz",
    "regularSeasonRecord": "21-13",
    "divisionTitles": "0",
    "playoffAppearances": "1",
    "playoffRecord": "2-1",
    "superBowlAppearances": "0",
    "superBowlWins": "0",
    "franchiseMvps": "1"
  },
  "griffins": {
    "rebranded": "No",
    "owner": "LjSalty",
    "regularSeasonRecord": "23-11",
    "divisionTitles": "2",
    "playoffAppearances": "2",
    "playoffRecord": "3-2",
    "superBowlAppearances": "0",
    "superBowlWins": "0",
    "franchiseMvps": "0"
  },
  "guardians": {
    "rebranded": "No",
    "owner": "Fly",
    "regularSeasonRecord": "14-20",
    "divisionTitles": "1",
    "playoffAppearances": "1",
    "playoffRecord": "0-1",
    "superBowlAppearances": "0",
    "superBowlWins": "0",
    "franchiseMvps": "0"
  },
  "kloud-nine": {
    "rebranded": "No",
    "owner": "No Hate",
    "regularSeasonRecord": "25-9",
    "divisionTitles": "1",
    "playoffAppearances": "2",
    "playoffRecord": "2-2",
    "superBowlAppearances": "0",
    "superBowlWins": "0",
    "franchiseMvps": "0"
  },
  "kush": {
    "rebranded": "Yes — formerly Tribe",
    "owner": "Father Figure",
    "regularSeasonRecord": "14-20",
    "divisionTitles": "1",
    "playoffAppearances": "1",
    "playoffRecord": "1-1",
    "superBowlAppearances": "0",
    "superBowlWins": "0",
    "franchiseMvps": "0"
  },
  "lake-hawks": {
    "rebranded": "No",
    "owner": "ChubyGuys",
    "regularSeasonRecord": "16-18",
    "divisionTitles": "0",
    "playoffAppearances": "1",
    "playoffRecord": "0-1",
    "superBowlAppearances": "0",
    "superBowlWins": "0",
    "franchiseMvps": "0"
  },
  "metros": {
    "rebranded": "No",
    "owner": "Jmanziel",
    "regularSeasonRecord": "21-13",
    "divisionTitles": "1",
    "playoffAppearances": "1",
    "playoffRecord": "0-1",
    "superBowlAppearances": "0",
    "superBowlWins": "0",
    "franchiseMvps": "0"
  },
  "minions": {
    "rebranded": "No",
    "owner": "Phatts",
    "regularSeasonRecord": "8-26",
    "divisionTitles": "0",
    "playoffAppearances": "0",
    "playoffRecord": "0-0",
    "superBowlAppearances": "0",
    "superBowlWins": "0",
    "franchiseMvps": "0"
  },
  "mob": {
    "rebranded": "No",
    "owner": "Rev",
    "regularSeasonRecord": "13-21",
    "divisionTitles": "0",
    "playoffAppearances": "0",
    "playoffRecord": "0-0",
    "superBowlAppearances": "0",
    "superBowlWins": "0",
    "franchiseMvps": "0"
  },
  "ocelots": {
    "rebranded": "Yes — formerly Super Sonics",
    "owner": "Brando",
    "regularSeasonRecord": "21-13",
    "divisionTitles": "1",
    "playoffAppearances": "1",
    "playoffRecord": "0-1",
    "superBowlAppearances": "0",
    "superBowlWins": "0",
    "franchiseMvps": "0"
  },
  "omnitrix": {
    "rebranded": "No",
    "owner": "Kenny",
    "regularSeasonRecord": "27-7",
    "divisionTitles": "1",
    "playoffAppearances": "1",
    "playoffRecord": "3-0",
    "superBowlAppearances": "1",
    "superBowlWins": "1",
    "franchiseMvps": "0"
  },
  "order": {
    "rebranded": "No",
    "owner": "Yak Sparks",
    "regularSeasonRecord": "22-11-1",
    "divisionTitles": "1",
    "playoffAppearances": "1",
    "playoffRecord": "2-1",
    "superBowlAppearances": "0",
    "superBowlWins": "0",
    "franchiseMvps": "0"
  },
  "overdrive": {
    "rebranded": "No",
    "owner": "Sushi",
    "regularSeasonRecord": "16-18",
    "divisionTitles": "1",
    "playoffAppearances": "1",
    "playoffRecord": "0-1",
    "superBowlAppearances": "0",
    "superBowlWins": "0",
    "franchiseMvps": "0"
  },
  "pheonixes": {
    "rebranded": "No",
    "owner": "JBX",
    "regularSeasonRecord": "19-15",
    "divisionTitles": "0",
    "playoffAppearances": "0",
    "playoffRecord": "0-0",
    "superBowlAppearances": "0",
    "superBowlWins": "0",
    "franchiseMvps": "0"
  },
  "rhode-runners": {
    "rebranded": "No",
    "owner": "Jimmy Mcgill",
    "regularSeasonRecord": "9-25",
    "divisionTitles": "0",
    "playoffAppearances": "0",
    "playoffRecord": "0-0",
    "superBowlAppearances": "0",
    "superBowlWins": "0",
    "franchiseMvps": "0"
  },
  "sharks": {
    "rebranded": "Yes — formerly Gorillas",
    "owner": "Salty Bathwater",
    "regularSeasonRecord": "4-30",
    "divisionTitles": "0",
    "playoffAppearances": "0",
    "playoffRecord": "0-0",
    "superBowlAppearances": "0",
    "superBowlWins": "0",
    "franchiseMvps": "0"
  },
  "sorcerers": {
    "rebranded": "No",
    "owner": "Mikey J",
    "regularSeasonRecord": "21-13",
    "divisionTitles": "0",
    "playoffAppearances": "1",
    "playoffRecord": "0-1",
    "superBowlAppearances": "0",
    "superBowlWins": "0",
    "franchiseMvps": "0"
  },
  "speed-racers": {
    "rebranded": "No",
    "owner": "ColeWorld",
    "regularSeasonRecord": "30-4",
    "divisionTitles": "1",
    "playoffAppearances": "2",
    "playoffRecord": "4-1",
    "superBowlAppearances": "1",
    "superBowlWins": "1",
    "franchiseMvps": "1"
  },
  "stars": {
    "rebranded": "No",
    "owner": "Mazi",
    "regularSeasonRecord": "10-24",
    "divisionTitles": "0",
    "playoffAppearances": "0",
    "playoffRecord": "0-0",
    "superBowlAppearances": "0",
    "superBowlWins": "0",
    "franchiseMvps": "0"
  },
  "stingers": {
    "rebranded": "Yes — formerly Long Horns",
    "owner": "Clutch",
    "regularSeasonRecord": "14-20",
    "divisionTitles": "1",
    "playoffAppearances": "1",
    "playoffRecord": "1-1",
    "superBowlAppearances": "0",
    "superBowlWins": "0",
    "franchiseMvps": "0"
  },
  "supermen": {
    "rebranded": "No",
    "owner": "Zero",
    "regularSeasonRecord": "19-15",
    "divisionTitles": "1",
    "playoffAppearances": "2",
    "playoffRecord": "1-2",
    "superBowlAppearances": "0",
    "superBowlWins": "0",
    "franchiseMvps": "0"
  },
  "surfers": {
    "rebranded": "No",
    "owner": "SouliumZ",
    "regularSeasonRecord": "9-25",
    "divisionTitles": "0",
    "playoffAppearances": "0",
    "playoffRecord": "0-0",
    "superBowlAppearances": "0",
    "superBowlWins": "0",
    "franchiseMvps": "0"
  },
  "thunder-birds": {
    "rebranded": "No",
    "owner": "Father",
    "regularSeasonRecord": "16-18",
    "divisionTitles": "1",
    "playoffAppearances": "1",
    "playoffRecord": "0-1",
    "superBowlAppearances": "0",
    "superBowlWins": "0",
    "franchiseMvps": "0"
  },
  "vodoo": {
    "rebranded": "No",
    "owner": "Sebb",
    "regularSeasonRecord": "25-9",
    "divisionTitles": "1",
    "playoffAppearances": "2",
    "playoffRecord": "5-2",
    "superBowlAppearances": "2",
    "superBowlWins": "0",
    "franchiseMvps": "0"
  },
  "volts": {
    "rebranded": "Yes — formerly Suits",
    "owner": "Dom",
    "regularSeasonRecord": "12-22",
    "divisionTitles": "0",
    "playoffAppearances": "0",
    "playoffRecord": "0-0",
    "superBowlAppearances": "0",
    "superBowlWins": "0",
    "franchiseMvps": "0"
  }
};
